variable "key_name" {
  type        = string
  default     = "test-task-key-pair"
  description = "Key-pair generated by Terraform"
}

variable "region" {
  type        = string
  default     = "eu-central-1"
  description = "Region for the infrastructure"
}

variable "instance_type" {
  type        = string
  default     = "t2.micro"
  description = "Instance type for servers"
}

variable "vpc_cidr_block" { 
  type        = string
  default     = "172.16.0.0/16" 
  description = "CIDR block for VPC"
}

variable "public_cidr_block" {
  type        = string
  default     = "172.16.1.0/24"
  description = "CIDR block for public subnet"
}

variable "public_availability_zone" {
  type        = string
  default     = "eu-central-1a"
  description = "Availability zone for public subnet"
}

variable "private_cidr_block" {
  type        = string
  default     = "172.16.2.0/24"
  description = "CIDR block for private subnet"
}

variable "private_availability_zone" {
  type        = string
  default     = "eu-central-1b"
  description = "Availability zone for private subnet"
}

variable "nat_cidr_block" {
  type        = string
  default     = "0.0.0.0/0"
  description = "NAT CIDR block"
}